remote_theme: just-the-docs/just-the-docs
color_scheme: light
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
callouts_level: loud # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false